{"name": "Ошибка проверки получения заказов неавторизованного пользователя", "status": "passed", "start": 1718881376953, "stop": 1718881378030, "uuid": "6c2ae263-8a20-489e-85a4-defbb691b507", "historyId": "54fbe1755115c45c0699b5e698cf2feb", "testCaseId": "54fbe1755115c45c0699b5e698cf2feb", "fullName": "tests.test_get_orders.TestGetUserOrders#test_getting_order_unauthorized_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "LAPTOP-8BB0DG15"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}