{"name": "Ошибка при проверке пользователя с некорректным логином", "status": "passed", "start": 1718881384279, "stop": 1718881385225, "uuid": "6b877a66-b5da-47e6-bbe9-2aa73a57f94c", "historyId": "c2cfa4cfdcfb6b394e5f7e8b771ee4a4", "testCaseId": "c2cfa4cfdcfb6b394e5f7e8b771ee4a4", "fullName": "tests.test_login_user.TestLoginUser#test_login_incorrect_email_failed_result", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-8BB0DG15"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}